---
# Secret with GitHub PAT token (still needed for GitHub!)
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: arc-system
type: Opaque
stringData:
  github_token: "ghp_1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q"
                # Replace with your actual GitHub PAT
